name: Build and Deploy Voting Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Deploy
        uses: appleboy/ssh-action@master
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          SCOPE: 'mainnet'
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ vars.CHAT_ID }}
          REGISTRY_API_URL: ${{ vars.REGISTRY_API_URL }}
          REGISTRY_API_TOKEN: ${{ secrets.REGISTRY_API_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: MNEMONIC,SCOPE,BOT_TOKEN,CHAT_ID,REGISTRY_API_URL,REGISTRY_API_TOKEN
          script: |
            # set node env
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use 20
            
            # checkout
            cd ~/cosmos-voting-bot
            git pull origin main
            
            # build cosmos-voting-bot
            cd ~/cosmos-voting-bot
            npm install
            NODE_ENV=production npm run build
            
            # generate ecosystem.config.json
            cat <<EOT > ~/cosmos-voting-bot/ecosystem.config.json
            {
              "apps": [
                {
                  "name": "cosmos-voting-bot",
                  "cwd": "/home/votingbot/cosmos-voting-bot",
                  "script": "npm",
                  "args": "start",
                  "autorestart": true,
                  "restart_delay": 1000,
                  "env": {
                    "MNEMONIC": "$MNEMONIC",
                    "SCOPE": "$SCOPE",
                    "BOT_TOKEN": "$BOT_TOKEN",
                    "CHAT_ID": "$CHAT_ID",
                    "REGISTRY_API_URL": "$REGISTRY_API_URL",
                    "REGISTRY_API_TOKEN": "$REGISTRY_API_TOKEN"
                  }
                }
              ]
            }
            EOT
            
            # restart pm2
            pm2 restart ~/cosmos-voting-bot/ecosystem.config.json
